### ISSUE TITLE
Issue with large collection

### ISSUE THREAD

**Issue by Epsilon748** [yukinogatari/Mangle#1]
It looks like there is an issue with attempting to create a .cbz file with extraordinarily large series. This comes up in the log when the file reaches exactly 2GB in the nook color format:

Traceback (most recent call last):
  File "convert.pyc", line 144, in onTimer
  File "zipfile.pyc", line 1097, in writestr
  File "zipfile.pyc", line 995, in _writecheck
zipfile.LargeZipFile: Zipfile size would require ZIP64 extensions

**Comment by yukinogatari** [comment]
That's just how the zipfile library works. I didn't think anyone would need (or want) CBZ files >2GB, so I didn't bother setting the flag in the object constructor. I uploaded a new version of convert.py that **should** take care of it, but because it takes so long to convert that much data, I haven't tested it extensively.
